language: php

php:
    - '7.0'
    - '7.1'
    - '7.2'

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer install --no-interaction

script:
    - ./vendor/bin/phpstan analyze --configuration=phpstan.neon --level=max --no-interaction --no-progress src/ tests/ bin/
    - ./vendor/bin/phpunit
